# ==========================================
# ETAPE 1 : Construction de l'application
# ==========================================

# Utilise l'image officielle Python 3.11 version Slim.
# Cette image contient déjà Python et pip.
FROM python:3.11-slim AS build

# Définit le dossier de travail à l'intérieur du conteneur.
# Toutes les commandes suivantes seront exécutées dans /app.
WORKDIR /app

# Copie uniquement le fichier requirements.txt.
# Cette méthode permet à Docker d'utiliser son cache si les dépendances
# ne changent pas entre deux constructions.
COPY requirements.txt .

# Installe toutes les bibliothèques Python nécessaires au projet.
# --no-cache-dir évite de conserver le cache de pip afin
# de réduire la taille finale de l'image.
RUN pip install --no-cache-dir -r requirements.txt

# Copie ensuite tous les fichiers du projet
# (manage.py, applications, templates, static, etc.).
COPY . .



# ==========================================
# ETAPE 2 : Image de production
# ==========================================

# Utilise de nouveau une image Python légère.
# Cette image servira uniquement à exécuter l'application.
FROM python:3.11-slim

# Définit le dossier de travail.
WORKDIR /app

# Copie toute l'application construite lors de la première étape.
COPY --from=build /app /app

# Indique que Django écoutera sur le port 8000.
EXPOSE 8000

# Définit la commande principale exécutée au démarrage.
ENTRYPOINT ["python3", "manage.py"]

# Les paramètres transmis à ENTRYPOINT.
# Docker exécutera automatiquement :
#
# python3 manage.py runserver 0.0.0.0:8000
#
CMD ["runserver", "0.0.0.0:8000"]

