# Etape 1 : build

FROM python3:3.11-slim as build

# Définit le répertoire de travail à l'intérieur du conteneur.
# Toutes les commandes suivantes seront exécutées dans /app.
WORKDIR /app

# Copie uniquement le fichier requirements.txt depuis le projet
# vers le dossier /app du conteneur.
COPY requirements.txt /app/

# Installe toutes les dépendances Python indiquées
# dans le fichier requirements.txt.
RUN pip3 install --break-system-packages --no-cache-dir -r requirements.txt

COPY  . .

# etape 2 : production

FROM python3:3.11-slim

COPY --from=builder /app /app

# Définit le répertoire de travail à l'intérieur du conteneur.
# Toutes les commandes suivantes seront exécutées dans /app.
WORKDIR /app

# Informe Docker que l'application écoute sur le port 8000.
# Cela ne publie pas automatiquement le port.
EXPOSE 8000

# Commande principale exécutée lorsque le conteneur démarre.
# Elle lance le fichier manage.py.
ENTRYPOINT ["python3", "manage.py"]

# Arguments ajoutés à ENTRYPOINT.
# La commande finale sera :
CMD ["runserver", "0.0.0.0:8000"]

