# ==========================
# ETAPE 1 : Construction (Builder)
# ==========================

# Utilise l'image officielle Python 3.11 légère.
# Cette image contient déjà Python et pip.
FROM python:3.11-slim AS base

# Définit le dossier de travail dans le conteneur.
# Toutes les commandes suivantes seront exécutées dans /app.
WORKDIR /app

# Copie uniquement le fichier requirements.txt.
# Cela permet à Docker d'utiliser son cache si ce fichier ne change pas.
COPY requirements.txt .

# Installe toutes les dépendances Python du projet.
# --no-cache-dir évite de conserver le cache pip afin de réduire la taille de l'image.
RUN pip install --no-cache-dir -r requirements.txt

# Copie ensuite tous les fichiers du projet dans le conteneur.
COPY . .



# ==========================
# ETAPE 2 : Image finale (Production)
# ==========================

# Utilise une image Distroless.
# Cette image est très légère et plus sécurisée car elle ne contient
# ni shell, ni gestionnaire de paquets, ni outils inutiles.
FROM gcr.io/distroless/python3

# Définit le dossier de travail.
WORKDIR /app

# Copie toutes les bibliothèques Python installées depuis l'image de construction.
COPY --from=base /usr/local/lib/python3.11 /usr/local/lib/python3.11

# Copie les exécutables Python (pip, python, etc.).
COPY --from=base /usr/local/bin /usr/local/bin

# Copie le projet Django.
COPY --from=base /app /app

# Indique que l'application écoute sur le port 8000.
EXPOSE 8000

# Définit la commande principale exécutée au démarrage.
# Elle lance le fichier manage.py.
ENTRYPOINT ["python3", "manage.py"]

# Arguments transmis automatiquement à ENTRYPOINT.
# La commande exécutée sera :
#
# python3 manage.py runserver 0.0.0.0:8000
#
CMD ["runserver", "0.0.0.0:8000"]
